### PR TITLE
Fix undefined behavior in interval_bounds::reverse_right()

### PR DESCRIPTION
**Pull request by avikivity**
Found by gcc's ubsan. See commit log for details.

### CODE REVIEW

**Comment by avikivity** [comment]
Only the last commit is mine, because I based my commit on master but github wants to pull into develop. Let me know if I should redo it based on develop, or retarget the pull request into master.

**Comment by duarten** [comment]
+1

**Comment by pdimov** [comment]
Pull requests should be based on develop, yes.

**Comment by avikivity** [comment]
@pdimov I rebased on top of develop and force-pushed.

**Pull request merged**
